services:
  - type: web
    name: without-token-july
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    repo: https://github.com/iryme786/Without-token-bot-july
    branch: main
    autoDeploy: false
    envVars:
      - key: BOT_TOKEN
        sync: false
      - key: API_ID
        sync: false
      - key: API_HASH
        sync: false
      - key: OWNER
        sync: false
      - key: CREDIT
        sync: false
      #- key: WEBHOOK
        #sync: false
      - key: PORT
        value: 8000  # Default port value, update if needed
